name: Adds all issues that don't include the 'bug' or 'needs-triage' labels to project board

on:
  issues:
    types:
      - opened
      - labeled
      - assigned
      - reopened
  pull_request:
    types:
      - opened
      - labeled
      - assigned
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/wheelnext/projects/4
          github-token: ${{ secrets.CI_TOKEN }}
          labeled: tracked
          values: Triage
